In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/Cleaned Dataset/Merged_data.csv')

In [ ]:
df.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                 34
Income composition of resources    167
Schooling                          163
Male_suicide_rate                   10
Female_suicide_rate                 10
suicide_rate                        10
Male_homicides                      10
Female_homicides                    10
Homicides                           10
Male_bmi                            24
Female_bmi                          24
bmi                                 34
Sanitation                          36
GDP                                 47
Population                           2
dtype: int64

In [ ]:
country_names = list(df.Country.unique())

In [ ]:
dict1 = dict()
for country in country_names:
  country_no = df[df.Country==country]['Country'].count()
  dict1[country] = country_no

sorted_dict = sorted(dict1.items(), key=lambda x:x[1])
# sorted_dict

In [ ]:
l = list()
for i in range(len(sorted_dict)):
  if sorted_dict[i][1] < 16:
    l.append(sorted_dict[i][0])

In [ ]:
df1 = df[~df.Country.isin(l)]

In [ ]:
# df1.drop(['Unnamed: 0'], axis = 1, inplace=True)
# df1.sort_values(by=['Country','Year'], ignore_index=True,inplace=True)

In [ ]:
df1.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                 32
Income composition of resources    160
Schooling                          160
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                            22
Female_bmi                          22
bmi                                 32
Sanitation                          36
GDP                                 45
Population                           0
dtype: int64

In [ ]:
df1[df1.Female_bmi.isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,NaN,NaN,NaN,NaN,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,NaN,NaN,NaN,NaN,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,NaN,NaN,NaN,NaN,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,NaN,NaN,NaN,NaN,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,NaN,NaN,NaN,NaN,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,NaN,NaN,NaN,NaN,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,NaN,NaN,NaN,NaN,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,NaN,NaN,NaN,NaN,NaN,8417823.0
2417,2417,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,...,6.86,23.90,6.01,14.95,NaN,NaN,NaN,NaN,1.458625e+10,8823888.0
2418,2418,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,...,6.71,23.21,5.86,14.53,NaN,NaN,NaN,NaN,1.223126e+10,9229227.0
2419,2419,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,...,6.64,22.70,5.88,14.29,NaN,NaN,NaN,NaN,1.460207e+10,9714419.0
2420,2420,South Sudan,2011,Developing,55.4,355.0,27.0,NaN,0.000000,41.0,...,6.61,22.33,5.88,14.11,NaN,NaN,NaN,6.87,1.490731e+10,10243050.0
2421,2421,South Sudan,2012,Developing,56.0,347.0,26.0,NaN,38.338232,40.0,...,6.71,21.94,5.86,13.90,NaN,NaN,NaN,7.80,1.193147e+10,10701604.0
2422,2422,South Sudan,2013,Developing,56.4,345.0,26.0,NaN,47.444530,40.0,...,6.47,22.10,5.93,14.02,NaN,NaN,NaN,8.78,1.842647e+10,11106031.0
2423,2423,South Sudan,2014,Developing,56.6,343.0,26.0,NaN,46.074469,39.0,...,6.22,22.53,6.10,14.32,NaN,NaN,NaN,9.81,1.396221e+10,11213284.0
2424,2424,South Sudan,2015,Developing,57.3,332.0,26.0,NaN,0.000000,39.0,...,6.41,22.93,6.36,14.65,NaN,NaN,NaN,10.89,1.199780e+10,11194299.0
2467,2467,Sudan,2010,Developing,62.5,243.0,62.0,1.77,172.009788,92.0,...,5.15,10.13,3.21,6.66,NaN,NaN,NaN,28.24,7.415119e+10,33739933.0
2468,2468,Sudan,2011,Developing,62.7,241.0,61.0,2.12,196.689215,91.0,...,5.28,9.97,3.22,6.59,NaN,NaN,NaN,29.57,7.840342e+10,34419624.0
2469,2469,Sudan,2012,Developing,63.2,235.0,61.0,0.01,220.522192,89.0,...,5.09,9.80,3.20,6.49,NaN,NaN,NaN,30.92,6.319550e+10,35159792.0
2470,2470,Sudan,2013,Developing,63.5,232.0,60.0,0.01,227.835321,88.0,...,5.11,9.63,3.19,6.41,NaN,NaN,NaN,32.29,6.602660e+10,35990704.0
2471,2471,Sudan,2014,Developing,63.8,229.0,59.0,0.01,253.608651,86.0,...,4.99,9.47,3.19,6.32,NaN,NaN,NaN,33.67,7.681833e+10,37003245.0
2472,2472,Sudan,2015,Developing,64.1,225.0,58.0,NaN,0.000000,85.0,...,4.89,9.28,3.15,6.21,NaN,NaN,NaN,35.07,8.498513e+10,38171178.0

Neighbouring countries of Sudan are Libya, South Sudan, Ethiopia, Eritrea, Central African Republic, Chad, Egypt

In [ ]:
df_sudan1 = df1[(df1.Country.isin(['Libya', 'Ethiopia', 'Eritrea', 'Central African Republic', 'Chad', 'Egypt'])) & (df1.Year>2009)]
df_sudan2 = df1[df1.Country.isin(['Libya', 'Ethiopia', 'Eritrea', 'Central African Republic', 'Chad', 'Egypt'])]

In [ ]:
g1 = df_sudan1.groupby('Year').agg({'Male_bmi': 'mean', 'Female_bmi': 'mean'})
g2 = df_sudan2.groupby('Year').agg({'bmi': 'mean'})
print(g1)
print()
print(g2)

       Male_bmi  Female_bmi
Year
2010  17.081667   17.784167
2011  17.116667   17.797500
2012  17.150000   17.814167
2013  17.187500   17.835000
2014  17.225000   17.856667
2015  17.265000   17.883333

            bmi
Year
2000  17.146667
2001  17.185833
2002  17.228333
2003  17.263333
2004  17.295833
2005  17.324167
2006  17.348333
2007  17.371667
2008  17.390833
2009  17.410000
2010  17.430000
2011  17.451667
2012  17.479167
2013  17.508333
2014  17.539167
2015  17.570833

In [ ]:
sudan1 = df1[(df1['Country'] == 'Sudan')& (df['Year']>2009)]
sudan2 = df1[df1['Country'] == 'Sudan']

<ipython-input-14-8f185638d05b>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sudan1 = df1[(df1['Country'] == 'Sudan')& (df['Year']>2009)]

In [ ]:
df1.loc[sudan1.index, 'Female_bmi'] = g1['Female_bmi'].values
df1.loc[sudan1.index, 'Male_bmi'] = g1['Male_bmi'].values
df1.loc[sudan2.index, 'bmi'] = g2['bmi'].values

In [ ]:
df1[df1.Country=='Sudan']

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
2457,2457,Sudan,2000,Developing,58.6,284.0,71.0,1.76,30.860010,109.0,...,5.56,10.69,4.90,7.81,21.500000,22.200000,17.146667,20.59,1.225742e+10,26298773.0
2458,2458,Sudan,2001,Developing,58.9,283.0,71.0,1.81,28.880697,108.0,...,5.44,10.91,4.64,7.78,21.600000,22.200000,17.185833,20.61,1.571649e+10,26947253.0
2459,2459,Sudan,2002,Developing,59.4,277.0,70.0,1.59,30.622875,106.0,...,5.45,11.12,4.33,7.74,21.700000,22.300000,17.228333,20.62,1.813684e+10,27570318.0
2460,2460,Sudan,2003,Developing,59.6,278.0,69.0,1.74,35.352647,104.0,...,5.35,11.30,4.06,7.69,21.800000,22.400000,17.263333,20.64,2.135558e+10,28188977.0
2461,2461,Sudan,2004,Developing,59.7,278.0,68.0,1.59,37.044800,102.0,...,5.29,11.44,3.79,7.63,21.900000,22.500000,17.295833,20.65,2.664549e+10,28831550.0
2462,2462,Sudan,2005,Developing,67.0,261.0,66.0,1.55,37.590396,101.0,...,5.39,11.40,3.58,7.50,22.000000,22.600000,17.324167,21.85,3.518211e+10,29540577.0
2463,2463,Sudan,2006,Developing,61.0,26.0,66.0,1.90,60.336857,99.0,...,5.30,11.22,3.39,7.31,22.100000,22.700000,17.348333,23.05,4.526452e+10,30332968.0
2464,2464,Sudan,2007,Developing,61.4,254.0,65.0,2.01,86.131669,97.0,...,5.23,11.05,3.21,7.13,22.200000,22.800000,17.371667,24.33,5.944014e+10,31191163.0
2465,2465,Sudan,2008,Developing,61.8,251.0,64.0,2.01,128.636271,95.0,...,5.19,10.70,3.24,6.97,22.300000,23.000000,17.390833,25.62,6.483194e+10,32065241.0
2466,2466,Sudan,2009,Developing,62.0,248.0,63.0,1.99,17.053693,94.0,...,5.22,10.40,3.23,6.81,22.400000,23.100000,17.410000,26.92,5.831619e+10,32948155.0
2467,2467,Sudan,2010,Developing,62.5,243.0,62.0,1.77,172.009788,92.0,...,5.15,10.13,3.21,6.66,17.081667,17.784167,17.430000,28.24,7.415119e+10,33739933.0
2468,2468,Sudan,2011,Developing,62.7,241.0,61.0,2.12,196.689215,91.0,...,5.28,9.97,3.22,6.59,17.116667,17.797500,17.451667,29.57,7.840342e+10,34419624.0
2469,2469,Sudan,2012,Developing,63.2,235.0,61.0,0.01,220.522192,89.0,...,5.09,9.80,3.20,6.49,17.150000,17.814167,17.479167,30.92,6.319550e+10,35159792.0
2470,2470,Sudan,2013,Developing,63.5,232.0,60.0,0.01,227.835321,88.0,...,5.11,9.63,3.19,6.41,17.187500,17.835000,17.508333,32.29,6.602660e+10,35990704.0
2471,2471,Sudan,2014,Developing,63.8,229.0,59.0,0.01,253.608651,86.0,...,4.99,9.47,3.19,6.32,17.225000,17.856667,17.539167,33.67,7.681833e+10,37003245.0
2472,2472,Sudan,2015,Developing,64.1,225.0,58.0,NaN,0.000000,85.0,...,4.89,9.28,3.15,6.21,17.265000,17.883333,17.570833,35.07,8.498513e+10,38171178.0

In [ ]:
df1[df1.Female_bmi.isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,NaN,NaN,NaN,NaN,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,NaN,NaN,NaN,NaN,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,NaN,NaN,NaN,NaN,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,NaN,NaN,NaN,NaN,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,NaN,NaN,NaN,NaN,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,NaN,NaN,NaN,NaN,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,NaN,NaN,NaN,NaN,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,NaN,NaN,NaN,NaN,NaN,8417823.0
2417,2417,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,...,6.86,23.90,6.01,14.95,NaN,NaN,NaN,NaN,1.458625e+10,8823888.0
2418,2418,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,...,6.71,23.21,5.86,14.53,NaN,NaN,NaN,NaN,1.223126e+10,9229227.0
2419,2419,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,...,6.64,22.70,5.88,14.29,NaN,NaN,NaN,NaN,1.460207e+10,9714419.0
2420,2420,South Sudan,2011,Developing,55.4,355.0,27.0,NaN,0.000000,41.0,...,6.61,22.33,5.88,14.11,NaN,NaN,NaN,6.87,1.490731e+10,10243050.0
2421,2421,South Sudan,2012,Developing,56.0,347.0,26.0,NaN,38.338232,40.0,...,6.71,21.94,5.86,13.90,NaN,NaN,NaN,7.80,1.193147e+10,10701604.0
2422,2422,South Sudan,2013,Developing,56.4,345.0,26.0,NaN,47.444530,40.0,...,6.47,22.10,5.93,14.02,NaN,NaN,NaN,8.78,1.842647e+10,11106031.0
2423,2423,South Sudan,2014,Developing,56.6,343.0,26.0,NaN,46.074469,39.0,...,6.22,22.53,6.10,14.32,NaN,NaN,NaN,9.81,1.396221e+10,11213284.0
2424,2424,South Sudan,2015,Developing,57.3,332.0,26.0,NaN,0.000000,39.0,...,6.41,22.93,6.36,14.65,NaN,NaN,NaN,10.89,1.199780e+10,11194299.0

Neighbouring countries of South Sudan are Uganda, Sudan, Ethiopia, Kenya, Central African Republic, Congo

In [ ]:
df_south_sudan = df1[df1.Country.isin(['Uganda', 'Sudan', 'Ethiopia', 'Kenya', 'Central African Republic', 'Congo'])]

In [ ]:
g3 = df_south_sudan.groupby('Year').agg({'Male_bmi': 'mean', 'Female_bmi': 'mean', 'bmi': 'mean'})
print(g3)

       Male_bmi  Female_bmi        bmi
Year
2000  18.201111   19.004444  16.461944
2001  18.243889   19.042222  16.496806
2002  18.300000   19.107222  16.536389
2003  18.347222   19.164444  16.568056
2004  18.409444   19.214444  16.599306
2005  18.455000   19.260556  16.627361
2006  18.503889   19.311111  16.651389
2007  18.556667   19.358889  16.673611
2008  18.609444   19.427778  16.690972
2009  18.671111   19.473333  16.710833
2010  16.393611   17.067361  16.729167
2011  16.428611   17.076250  16.750278
2012  16.468333   17.088194  16.775694
2013  16.508750   17.101667  16.803889
2014  16.551667   17.116944  16.833194
2015  16.595833   17.136389  16.864306

In [ ]:
south_sudan = df1[df1['Country'] == 'South Sudan']
south_sudan

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,NaN,NaN,NaN,NaN,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,NaN,NaN,NaN,NaN,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,NaN,NaN,NaN,NaN,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,NaN,NaN,NaN,NaN,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,NaN,NaN,NaN,NaN,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,NaN,NaN,NaN,NaN,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,NaN,NaN,NaN,NaN,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,NaN,NaN,NaN,NaN,NaN,8417823.0
2417,2417,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,...,6.86,23.90,6.01,14.95,NaN,NaN,NaN,NaN,1.458625e+10,8823888.0
2418,2418,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,...,6.71,23.21,5.86,14.53,NaN,NaN,NaN,NaN,1.223126e+10,9229227.0
2419,2419,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,...,6.64,22.70,5.88,14.29,NaN,NaN,NaN,NaN,1.460207e+10,9714419.0
2420,2420,South Sudan,2011,Developing,55.4,355.0,27.0,NaN,0.000000,41.0,...,6.61,22.33,5.88,14.11,NaN,NaN,NaN,6.87,1.490731e+10,10243050.0
2421,2421,South Sudan,2012,Developing,56.0,347.0,26.0,NaN,38.338232,40.0,...,6.71,21.94,5.86,13.90,NaN,NaN,NaN,7.80,1.193147e+10,10701604.0
2422,2422,South Sudan,2013,Developing,56.4,345.0,26.0,NaN,47.444530,40.0,...,6.47,22.10,5.93,14.02,NaN,NaN,NaN,8.78,1.842647e+10,11106031.0
2423,2423,South Sudan,2014,Developing,56.6,343.0,26.0,NaN,46.074469,39.0,...,6.22,22.53,6.10,14.32,NaN,NaN,NaN,9.81,1.396221e+10,11213284.0
2424,2424,South Sudan,2015,Developing,57.3,332.0,26.0,NaN,0.000000,39.0,...,6.41,22.93,6.36,14.65,NaN,NaN,NaN,10.89,1.199780e+10,11194299.0

In [ ]:
df1.loc[south_sudan.index, 'Female_bmi'] = g3['Female_bmi'].values
df1.loc[south_sudan.index, 'Male_bmi'] = g3['Male_bmi'].values
df1.loc[south_sudan.index, 'bmi'] = g3['bmi'].values

In [ ]:
df1.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                 32
Income composition of resources    160
Schooling                          160
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                          36
GDP                                 45
Population                           0
dtype: int64

Handling missing values in **thinness 1-19 years** column

In [ ]:
df1[df1['thinness 1-19 years'].isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,18.201111,19.004444,16.461944,NaN,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,18.243889,19.042222,16.496806,NaN,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,18.300000,19.107222,16.536389,NaN,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,18.347222,19.164444,16.568056,NaN,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,18.409444,19.214444,16.599306,NaN,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,18.455000,19.260556,16.627361,NaN,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,18.503889,19.311111,16.651389,NaN,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,18.556667,19.358889,16.673611,NaN,NaN,8417823.0
2417,2417,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,...,6.86,23.90,6.01,14.95,18.609444,19.427778,16.690972,NaN,1.458625e+10,8823888.0
2418,2418,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,...,6.71,23.21,5.86,14.53,18.671111,19.473333,16.710833,NaN,1.223126e+10,9229227.0
2419,2419,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,...,6.64,22.70,5.88,14.29,16.393611,17.067361,16.729167,NaN,1.460207e+10,9714419.0
2420,2420,South Sudan,2011,Developing,55.4,355.0,27.0,NaN,0.000000,41.0,...,6.61,22.33,5.88,14.11,16.428611,17.076250,16.750278,6.87,1.490731e+10,10243050.0
2421,2421,South Sudan,2012,Developing,56.0,347.0,26.0,NaN,38.338232,40.0,...,6.71,21.94,5.86,13.90,16.468333,17.088194,16.775694,7.80,1.193147e+10,10701604.0
2422,2422,South Sudan,2013,Developing,56.4,345.0,26.0,NaN,47.444530,40.0,...,6.47,22.10,5.93,14.02,16.508750,17.101667,16.803889,8.78,1.842647e+10,11106031.0
2423,2423,South Sudan,2014,Developing,56.6,343.0,26.0,NaN,46.074469,39.0,...,6.22,22.53,6.10,14.32,16.551667,17.116944,16.833194,9.81,1.396221e+10,11213284.0
2424,2424,South Sudan,2015,Developing,57.3,332.0,26.0,NaN,0.000000,39.0,...,6.41,22.93,6.36,14.65,16.595833,17.136389,16.864306,10.89,1.199780e+10,11194299.0
2457,2457,Sudan,2000,Developing,58.6,284.0,71.0,1.76,30.860010,109.0,...,5.56,10.69,4.90,7.81,21.500000,22.200000,17.146667,20.59,1.225742e+10,26298773.0
2458,2458,Sudan,2001,Developing,58.9,283.0,71.0,1.81,28.880697,108.0,...,5.44,10.91,4.64,7.78,21.600000,22.200000,17.185833,20.61,1.571649e+10,26947253.0
2459,2459,Sudan,2002,Developing,59.4,277.0,70.0,1.59,30.622875,106.0,...,5.45,11.12,4.33,7.74,21.700000,22.300000,17.228333,20.62,1.813684e+10,27570318.0
2460,2460,Sudan,2003,Developing,59.6,278.0,69.0,1.74,35.352647,104.0,...,5.35,11.30,4.06,7.69,21.800000,22.400000,17.263333,20.64,2.135558e+10,28188977.0
2461,2461,Sudan,2004,Developing,59.7,278.0,68.0,1.59,37.044800,102.0,...,5.29,11.44,3.79,7.63,21.900000,22.500000,17.295833,20.65,2.664549e+10,28831550.0
2462,2462,Sudan,2005,Developing,67.0,261.0,66.0,1.55,37.590396,101.0,...,5.39,11.40,3.58,7.50,22.000000,22.600000,17.324167,21.85,3.518211e+10,29540577.0
2463,2463,Sudan,2006,Developing,61.0,26.0,66.0,1.90,60.336857,99.0,...,5.30,11.22,3.39,7.31,22.100000,22.700000,17.348333,23.05,4.526452e+10,30332968.0
2464,2464,Sudan,2007,Developing,61.4,254.0,65.0,2.01,86.131669,97.0,...,5.23,11.05,3.21,7.13,22.200000,22.800000,17.371667,24.33,5.944014e+10,31191163.0
2465,2465,Sudan,2008,Developing,61.8,251.0,64.0,2.01,128.636271,95.0,...,5.19,10.70,3.24,6.97,22.300000,23.000000,17.390833,25.62,6.483194e+10,32065241.0
2466,2466,Sudan,2009,Developing,62.0,248.0,63.0,1.99,17.053693,94.0,...,5.22,10.40,3.23,6.81,22.400000,23.100000,17.410000,26.92,5.831619e+10,32948155.0
2467,2467,Sudan,2010,Developing,62.5,243.0,62.0,1.77,172.009788,92.0,...,5.15,10.13,3.21,6.66,17.081667,17.784167,17.430000,28.24,7.415119e+10,33739933.0
2468,2468,Sudan,2011,Developing,62.7,241.0,61.0,2.12,196.689215,91.0,...,5.28,9.97,3.22,6.59,17.116667,17.797500,17.451667,29.57,7.840342e+10,34419624.0
2469,2469,Sudan,2012,Developing,63.2,235.0,61.0,0.01,220.522192,89.0,...,5.09,9.80,3.20,6.49,17.150000,17.814167,17.479167,30.92,6.319550e+10,35159792.0
2470,2470,Sudan,2013,Developing,63.5,232.0,60.0,0.01,227.835321,88.0,...,5.11,9.63,3.19,6.41,17.187500,17.835000,17.508333,32.29,6.602660e+10,35990704.0
2471,2471,Sudan,2014,Developing,63.8,229.0,59.0,0.01,253.608651,86.0,...,4.99,9.47,3.19,6.32,17.225000,17.856667,17.539167,33.67,7.681833e+10,37003245.0
2472,2472,Sudan,2015,Developing,64.1,225.0,58.0,NaN,0.000000,85.0,...,4.89,9.28,3.15,6.21,17.265000,17.883333,17.570833,35.07,8.498513e+10,38171178.0

In [ ]:
g4 = df_sudan2.groupby('Year').agg({'thinness 1-19 years': 'mean'})
g5 = df_south_sudan.groupby('Year').agg({'thinness 1-19 years': 'mean'})
print(g4)
print()
print(g5)

      thinness 1-19 years
Year
2000             5.900000
2001             5.766667
2002             7.150000
2003             5.516667
2004             6.916667
2005             6.800000
2006             6.716667
2007             6.583333
2008             8.000000
2009             7.900000
2010             7.816667
2011             6.200000
2012             6.100000
2013             6.016667
2014             5.933333
2015             5.850000

      thinness 1-19 years
Year
2000                 7.82
2001                 7.70
2002                 7.58
2003                 7.44
2004                 9.14
2005                 9.02
2006                 8.92
2007                 8.78
2008                 8.68
2009                 8.56
2010                 8.46
2011                 6.54
2012                 6.42
2013                 6.28
2014                 6.20
2015                 6.10

In [ ]:
df1.loc[sudan2.index, 'thinness 1-19 years'] = g4['thinness 1-19 years'].values
df1.loc[south_sudan.index, 'thinness 1-19 years'] = g5['thinness 1-19 years'].values

In [ ]:
df1.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                  0
Income composition of resources    160
Schooling                          160
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                          36
GDP                                 45
Population                           0
dtype: int64

handling missing values in **Sanitation** column

In [ ]:
df1[df1.Sanitation.isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
368,368,Brunei Darussalam,2000,Developing,74.4,16.0,0.0,0.37,11.796861,0.0,...,1.72,2.02,1.09,1.56,19.943333,19.930000,18.275000,NaN,6.001153e+09,333926.0
369,369,Brunei Darussalam,2001,Developing,74.7,19.0,0.0,0.47,1078.662440,0.0,...,1.29,1.58,0.88,1.23,20.030000,19.963333,18.335000,NaN,5.601091e+09,340748.0
370,370,Brunei Darussalam,2002,Developing,74.8,95.0,0.0,0.13,941.703687,0.0,...,1.50,1.40,0.56,0.99,20.090000,20.000000,18.410000,NaN,5.843329e+09,347463.0
371,371,Brunei Darussalam,2003,Developing,76.0,89.0,0.0,0.12,1406.511940,0.0,...,1.57,1.30,0.53,0.92,20.183333,20.036667,18.485000,NaN,6.557333e+09,354045.0
372,372,Brunei Darussalam,2004,Developing,76.4,89.0,0.0,0.11,1504.300040,0.0,...,1.78,1.14,0.56,0.86,20.250000,20.076667,18.565000,NaN,7.872333e+09,360461.0
373,373,Brunei Darussalam,2005,Developing,76.2,92.0,0.0,0.16,179.714781,0.0,...,1.94,1.35,0.58,0.97,20.353333,20.116667,18.645000,NaN,9.531403e+09,366717.0
374,374,Brunei Darussalam,2006,Developing,76.3,93.0,0.0,0.67,24.975329,0.0,...,2.43,1.67,0.79,1.24,20.423333,20.156667,18.730000,NaN,1.147070e+10,372808.0
705,705,Democratic People's Republic of Korea,2000,Developing,65.4,192.0,18.0,3.52,0.000000,25.0,...,10.29,8.64,3.60,6.06,19.083333,18.670000,17.420000,NaN,NaN,23367059.0
706,706,Democratic People's Republic of Korea,2001,Developing,66.6,177.0,16.0,2.53,0.000000,21.0,...,9.93,7.59,3.50,5.50,19.126667,18.653333,17.460000,NaN,NaN,23512522.0
1732,1732,Montenegro,2000,Developing,73.0,144.0,0.0,0.01,274.547260,0.0,...,18.94,6.36,2.21,4.26,21.026667,20.400000,18.205000,NaN,9.842976e+08,604950.0
1733,1733,Montenegro,2001,Developing,73.3,136.0,0.0,0.01,33.669814,0.0,...,17.69,6.34,2.24,4.26,21.053333,20.420000,18.245000,NaN,1.159869e+09,607389.0
1734,1734,Montenegro,2002,Developing,73.4,136.0,0.0,0.01,36.480240,0.0,...,17.81,6.33,2.25,4.26,21.110000,20.476667,18.280000,NaN,1.284685e+09,609828.0
1735,1735,Montenegro,2003,Developing,73.5,134.0,0.0,0.01,495.078296,0.0,...,18.34,5.64,2.03,3.81,21.173333,20.493333,18.315000,NaN,1.707710e+09,612267.0
1736,1736,Montenegro,2004,Developing,73.5,134.0,0.0,0.01,57.121901,0.0,...,18.45,5.29,1.83,3.53,21.236667,20.546667,18.350000,NaN,2.073234e+09,613353.0
1737,1737,Montenegro,2005,Developing,73.6,133.0,0.0,NaN,527.307672,0.0,...,18.72,5.68,1.90,3.76,21.270000,20.563333,18.390000,NaN,2.257174e+09,614261.0
2119,2119,Romania,2000,Developed,77.0,175.0,4.0,10.16,152.636890,5.0,...,11.33,5.67,1.88,3.73,19.500000,20.160000,17.260000,NaN,3.725326e+10,22442971.0
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,18.201111,19.004444,16.461944,NaN,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,18.243889,19.042222,16.496806,NaN,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,18.300000,19.107222,16.536389,NaN,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,18.347222,19.164444,16.568056,NaN,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,18.409444,19.214444,16.599306,NaN,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,18.455000,19.260556,16.627361,NaN,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,18.503889,19.311111,16.651389,NaN,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,18.556667,19.358889,16.673611,NaN,NaN,8417823.0
2417,2417,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,...,6.86,23.90,6.01,14.95,18.609444,19.427778,16.690972,NaN,1.458625e+10,8823888.0
2418,2418,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,...,6.71,23.21,5.86,14.53,18.671111,19.473333,16.710833,NaN,1.223126e+10,9229227.0
2419,2419,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,...,6.64,22.70,5.88,14.29,16.393611,17.067361,16.729167,NaN,1.460207e+10,9714419.0
2601,2601,Timor-Leste,2000,Developing,58.7,276.0,3.0,0.50,49.069672,4.0,...,4.88,6.75,1.78,4.29,17.530000,17.993333,16.185000,NaN,3.670879e+08,878360.0
2602,2602,Timor-Leste,2001,Developing,59.4,269.0,3.0,0.50,6.556583,4.0,...,4.94,6.73,1.72,4.25,17.550000,18.026667,16.205000,NaN,4.774435e+08,893001.0
2746,2746,United Arab Emirates,2000,Developing,74.2,17.0,1.0,1.64,262.958958,1.0,...,8.01,1.98,0.49,1.49,22.160000,22.666667,19.670000,NaN,1.043370e+11,3275333.0
2747,2747,United Arab Emirates,2001,Developing,74.5,14.0,1.0,1.67,243.753913,1.0,...,7.89,2.02,0.48,1.52,22.246667,22.710000,19.745000,NaN,1.033120e+11,3454198.0
2858,2858,Venezuela,2000,Developing,72.5,168.0,11.0,8.01,0.000000,13.0,...,6.35,76.53,7.41,42.09,21.400000,22.023333,19.155000,NaN,1.171410e+11,24427729.0
2859,2859,Venezuela,2001,Developing,72.5,169.0,10.0,8.05,0.000000,12.0,...,6.52,74.70,7.57,41.24,21.480000,22.090000,19.220000,NaN,1.229040e+11,24880203.0
2860,2860,Venezuela,2002,Developing,73.1,167.0,10.0,6.89,0.000000,12.0,...,6.18,87.33,9.83,48.68,21.563333,22.146667,19.275000,NaN,9.289359e+10,25330929.0
2861,2861,Venezuela,2003,Developing,72.4,172.0,10.0,6.30,0.000000,12.0,...,5.60,107.20,10.29,58.85,21.646667,22.203333,19.330000,NaN,8.362063e+10,25782029.0
2862,2862,Venezuela,2004,Developing,73.3,161.0,10.0,7.55,0.000000,11.0,...,5.06,87.99,8.86,48.49,21.726667,22.250000,19.380000,NaN,1.124530e+11,26226927.0

In [ ]:
df1.Sanitation.fillna(method='bfill', inplace=True)

<ipython-input-28-edb3232a1b92>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.Sanitation.fillna(method='bfill', inplace=True)

In [ ]:
# for c in df1[df1.Sanitation.isna()].Country.unique():
#   print(df1[df1.Country==c][['Country', 'Year', 'Sanitation']])
#   print()

In [ ]:
# for c in ['Brunei Darussalam',"Democratic People's Republic of Korea","Romania","South Sudan","United Arab Emirates"]:
#   df_c = df1[df1.Country == c]
#   df1.loc[df_c.index,'Sanitation'] = df1[df1.Country==c]['Sanitation'].fillna(method='bfill')

In [ ]:
# for c in df1[df1.Sanitation.isna()].Country.unique():
#   print(df1[df1.Country==c][['Country', 'Year', 'Sanitation']])
#   print()

Handling missing values in **GDP** column

In [ ]:
df1.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                  0
Income composition of resources    160
Schooling                          160
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                           0
GDP                                 45
Population                           0
dtype: int64

In [ ]:
df1[df1.GDP.isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
0,0,Afghanistan,2000,Developing,54.8,321.0,88.0,0.01,10.424960,122.0,...,7.71,16.71,2.43,9.78,17.086667,17.830000,15.875000,21.87,NaN,19542982.0
1,1,Afghanistan,2001,Developing,55.3,316.0,88.0,0.01,10.574728,122.0,...,7.89,16.44,2.43,9.64,17.116667,17.866667,15.925000,21.88,NaN,19688632.0
705,705,Democratic People's Republic of Korea,2000,Developing,65.4,192.0,18.0,3.52,0.000000,25.0,...,10.29,8.64,3.60,6.06,19.083333,18.670000,17.420000,75.20,NaN,23367059.0
706,706,Democratic People's Republic of Korea,2001,Developing,66.6,177.0,16.0,2.53,0.000000,21.0,...,9.93,7.59,3.50,5.50,19.126667,18.653333,17.460000,75.20,NaN,23512522.0
707,707,Democratic People's Republic of Korea,2002,Developing,67.6,167.0,14.0,3.08,0.000000,18.0,...,9.84,7.12,3.48,5.25,19.156667,18.666667,17.500000,75.20,NaN,23638411.0
708,708,Democratic People's Republic of Korea,2003,Developing,68.1,165.0,12.0,3.13,0.000000,15.0,...,9.43,6.70,3.67,5.15,19.193333,18.640000,17.530000,75.21,NaN,23781707.0
709,709,Democratic People's Republic of Korea,2004,Developing,68.4,165.0,11.0,3.13,0.000000,14.0,...,9.23,5.29,3.53,4.39,19.223333,18.656667,17.565000,75.22,NaN,23948930.0
710,710,Democratic People's Republic of Korea,2005,Developing,68.5,165.0,10.0,3.21,0.000000,13.0,...,9.04,6.08,3.38,4.70,19.260000,18.670000,17.605000,75.23,NaN,24100982.0
711,711,Democratic People's Republic of Korea,2006,Developing,68.5,165.0,10.0,3.28,0.000000,12.0,...,8.95,6.02,3.38,4.67,19.300000,18.693333,17.650000,75.24,NaN,24235761.0
712,712,Democratic People's Republic of Korea,2007,Developing,68.5,166.0,9.0,3.13,0.000000,12.0,...,8.93,6.19,3.60,4.87,19.343333,18.716667,17.705000,75.92,NaN,24356506.0
713,713,Democratic People's Republic of Korea,2008,Developing,68.6,164.0,9.0,3.16,0.000000,12.0,...,9.20,6.06,3.57,4.79,19.386667,18.746667,17.755000,76.61,NaN,24469047.0
714,714,Democratic People's Republic of Korea,2009,Developing,68.7,161.0,9.0,3.35,0.000000,11.0,...,9.13,6.09,3.60,4.82,19.433333,18.776667,17.815000,77.32,NaN,24581509.0
715,715,Democratic People's Republic of Korea,2010,Developing,69.0,157.0,8.0,3.12,0.000000,10.0,...,9.19,6.04,3.53,4.76,18.175000,17.560000,17.875000,78.03,NaN,24686435.0
716,716,Democratic People's Republic of Korea,2011,Developing,69.4,153.0,8.0,3.39,0.000000,10.0,...,9.24,5.98,3.45,4.68,18.245000,17.610000,17.935000,78.75,NaN,24783789.0
717,717,Democratic People's Republic of Korea,2012,Developing,69.8,149.0,7.0,3.61,0.000000,9.0,...,9.09,5.89,3.37,4.60,18.320000,17.660000,18.000000,79.47,NaN,24887770.0
718,718,Democratic People's Republic of Korea,2013,Developing,71.0,146.0,6.0,3.35,0.000000,8.0,...,9.12,5.80,3.32,4.53,18.390000,17.720000,18.060000,80.20,NaN,25001819.0
719,719,Democratic People's Republic of Korea,2014,Developing,73.0,142.0,6.0,0.01,0.000000,8.0,...,9.13,5.74,3.29,4.49,18.460000,17.770000,18.125000,80.93,NaN,25126131.0
720,720,Democratic People's Republic of Korea,2015,Developing,76.0,139.0,6.0,NaN,0.000000,7.0,...,9.47,5.67,3.26,4.44,18.540000,17.830000,18.195000,81.67,NaN,25258015.0
862,862,Eritrea,2012,Developing,63.6,274.0,6.0,0.01,0.000000,8.0,...,19.73,17.58,4.87,11.23,15.955000,16.645000,16.295000,11.54,NaN,3252596.0
863,863,Eritrea,2013,Developing,64.0,266.0,6.0,0.01,0.000000,8.0,...,19.24,17.59,4.98,11.29,15.995000,16.660000,16.325000,11.64,NaN,3296367.0
864,864,Eritrea,2014,Developing,64.4,261.0,5.0,0.01,0.000000,8.0,...,18.87,17.63,5.04,11.34,16.035000,16.680000,16.355000,11.74,NaN,3323425.0
865,865,Eritrea,2015,Developing,64.7,255.0,5.0,NaN,0.000000,7.0,...,18.69,17.76,5.10,11.44,16.085000,16.705000,16.390000,11.84,NaN,3340006.0
2217,2217,Sao Tome and Principe,2000,Developing,62.6,224.0,0.0,5.07,0.000000,0.0,...,2.24,8.97,4.39,6.65,18.760000,19.616667,17.375000,20.33,NaN,143714.0
2377,2377,Somalia,2000,Developing,55.0,355.0,45.0,0.01,0.000000,74.0,...,16.78,10.57,3.03,6.81,18.003333,18.723333,16.720000,20.17,NaN,8721465.0
2378,2378,Somalia,2001,Developing,57.0,352.0,46.0,0.01,0.000000,75.0,...,16.52,10.35,2.97,6.67,18.040000,18.780000,16.765000,20.78,NaN,9070747.0
2379,2379,Somalia,2002,Developing,58.0,348.0,47.0,0.01,0.000000,77.0,...,16.57,10.19,2.97,6.59,18.110000,18.836667,16.810000,21.38,NaN,9411103.0
2380,2380,Somalia,2003,Developing,51.1,344.0,48.0,0.01,0.000000,78.0,...,16.64,10.07,2.91,6.49,18.143333,18.893333,16.850000,22.13,NaN,9758281.0
2381,2381,Somalia,2004,Developing,51.2,341.0,49.0,0.01,0.000000,80.0,...,16.83,9.92,2.86,6.39,18.213333,18.910000,16.895000,22.88,NaN,10117354.0
2382,2382,Somalia,2005,Developing,51.6,334.0,50.0,0.01,0.000000,82.0,...,16.61,9.77,2.85,6.31,18.246667,18.963333,16.935000,23.87,NaN,10467292.0
2383,2383,Somalia,2006,Developing,51.5,337.0,51.0,0.01,0.000000,83.0,...,16.16,9.67,2.89,6.28,18.313333,19.010000,16.965000,24.86,NaN,10784973.0
2384,2384,Somalia,2007,Developing,51.5,34.0,52.0,0.01,0.000000,84.0,...,15.85,9.48,2.87,6.17,18.376667,19.053333,17.000000,24.56,NaN,11118092.0
2385,2385,Somalia,2008,Developing,51.9,336.0,52.0,0.01,0.000000,84.0,...,16.01,9.23,2.85,6.04,18.410000,19.100000,17.025000,25.90,NaN,11444870.0
2386,2386,Somalia,2009,Developing,52.2,335.0,52.0,0.01,0.000000,84.0,...,15.95,9.10,2.94,6.02,18.470000,19.110000,17.055000,27.26,NaN,11730037.0
2387,2387,Somalia,2010,Developing,52.4,336.0,52.0,0.01,0.000000,83.0,...,15.38,9.19,2.88,6.03,16.750000,17.440000,17.095000,28.63,NaN,12026649.0
2388,2388,Somalia,2011,Developing,53.1,329.0,51.0,0.01,0.000000,82.0,...,15.32,9.06,2.85,5.95,16.800000,17.465000,17.130000,30.02,NaN,12216837.0
2389,2389,Somalia,2012,Developing,53.1,336.0,51.0,0.01,0.000000,82.0,...,15.28,8.65,2.74,5.69,16.855000,17.500000,17.175000,31.00,NaN,12440326.0
2409,2409,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,...,7.89,30.91,7.43,19.12,18.201111,19.004444,16.461944,6.87,NaN,6114440.0
2410,2410,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,...,7.44,30.04,7.28,18.62,18.243889,19.042222,16.496806,6.87,NaN,6394431.0
2411,2411,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,...,7.26,29.17,7.07,18.08,18.300000,19.107222,16.536389,6.87,NaN,6686100.0
2412,2412,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,...,7.26,28.35,6.83,17.56,18.347222,19.164444,16.568056,6.87,NaN,6992367.0
2413,2413,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,...,7.23,27.44,6.59,16.99,18.409444,19.214444,16.599306,6.87,NaN,7317118.0
2414,2414,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,...,7.10,26.38,6.37,16.35,18.455000,19.260556,16.627361,6.87,NaN,7662654.0
2415,2415,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,...,7.08,25.51,6.18,15.83,18.503889,19.311111,16.651389,6.87,NaN,8029517.0
2416,2416,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,...,7.00,24.62,6.07,15.33,18.556667,19.358889,16.673611,6.87,NaN,8417823.0
2873,2873,Venezuela,2015,Developing,74.1,157.0,9.0,NaN,0.000000,10.0,...,2.37,114.80,8.17,61.18,19.715000,19.720000,19.715000,94.85,NaN,30529716.0

In [ ]:
df1.loc[df1[df1.Country=='Afghanistan'].index,'GDP'] = df1[df1.Country=='Afghanistan']['GDP'].fillna(method='bfill')
df1.loc[df1[df1.Country=='Eritrea'].index,'GDP'] = df1[df1.Country=='Eritrea']['GDP'].fillna(method='ffill')
df1.loc[df1[df1.Country=='Sao Tome and Principe'].index,'GDP'] = df1[df1.Country=='Sao Tome and Principe']['GDP'].fillna(method='bfill')
df1.loc[df1[df1.Country=='Somalia'].index,'GDP'] = df1[df1.Country=='Somalia']['GDP'].fillna(method='bfill')
df1.loc[df1[df1.Country=='South Sudan'].index,'GDP'] = df1[df1.Country=='South Sudan']['GDP'].fillna(method='bfill')
df1.loc[df1[df1.Country=='Venezuela'].index,'GDP'] = df1[df1.Country=='Venezuela']['GDP'].fillna(method='ffill')

In [ ]:
df1[df1.GDP.isna()]

,Unnamed: 0,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,suicide_rate,Male_homicides,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population
705,705,Democratic People's Republic of Korea,2000,Developing,65.4,192.0,18.0,3.52,0.0,25.0,...,10.29,8.64,3.60,6.06,19.083333,18.670000,17.420,75.20,NaN,23367059.0
706,706,Democratic People's Republic of Korea,2001,Developing,66.6,177.0,16.0,2.53,0.0,21.0,...,9.93,7.59,3.50,5.50,19.126667,18.653333,17.460,75.20,NaN,23512522.0
707,707,Democratic People's Republic of Korea,2002,Developing,67.6,167.0,14.0,3.08,0.0,18.0,...,9.84,7.12,3.48,5.25,19.156667,18.666667,17.500,75.20,NaN,23638411.0
708,708,Democratic People's Republic of Korea,2003,Developing,68.1,165.0,12.0,3.13,0.0,15.0,...,9.43,6.70,3.67,5.15,19.193333,18.640000,17.530,75.21,NaN,23781707.0
709,709,Democratic People's Republic of Korea,2004,Developing,68.4,165.0,11.0,3.13,0.0,14.0,...,9.23,5.29,3.53,4.39,19.223333,18.656667,17.565,75.22,NaN,23948930.0
710,710,Democratic People's Republic of Korea,2005,Developing,68.5,165.0,10.0,3.21,0.0,13.0,...,9.04,6.08,3.38,4.70,19.260000,18.670000,17.605,75.23,NaN,24100982.0
711,711,Democratic People's Republic of Korea,2006,Developing,68.5,165.0,10.0,3.28,0.0,12.0,...,8.95,6.02,3.38,4.67,19.300000,18.693333,17.650,75.24,NaN,24235761.0
712,712,Democratic People's Republic of Korea,2007,Developing,68.5,166.0,9.0,3.13,0.0,12.0,...,8.93,6.19,3.60,4.87,19.343333,18.716667,17.705,75.92,NaN,24356506.0
713,713,Democratic People's Republic of Korea,2008,Developing,68.6,164.0,9.0,3.16,0.0,12.0,...,9.20,6.06,3.57,4.79,19.386667,18.746667,17.755,76.61,NaN,24469047.0
714,714,Democratic People's Republic of Korea,2009,Developing,68.7,161.0,9.0,3.35,0.0,11.0,...,9.13,6.09,3.60,4.82,19.433333,18.776667,17.815,77.32,NaN,24581509.0
715,715,Democratic People's Republic of Korea,2010,Developing,69.0,157.0,8.0,3.12,0.0,10.0,...,9.19,6.04,3.53,4.76,18.175000,17.560000,17.875,78.03,NaN,24686435.0
716,716,Democratic People's Republic of Korea,2011,Developing,69.4,153.0,8.0,3.39,0.0,10.0,...,9.24,5.98,3.45,4.68,18.245000,17.610000,17.935,78.75,NaN,24783789.0
717,717,Democratic People's Republic of Korea,2012,Developing,69.8,149.0,7.0,3.61,0.0,9.0,...,9.09,5.89,3.37,4.60,18.320000,17.660000,18.000,79.47,NaN,24887770.0
718,718,Democratic People's Republic of Korea,2013,Developing,71.0,146.0,6.0,3.35,0.0,8.0,...,9.12,5.80,3.32,4.53,18.390000,17.720000,18.060,80.20,NaN,25001819.0
719,719,Democratic People's Republic of Korea,2014,Developing,73.0,142.0,6.0,0.01,0.0,8.0,...,9.13,5.74,3.29,4.49,18.460000,17.770000,18.125,80.93,NaN,25126131.0
720,720,Democratic People's Republic of Korea,2015,Developing,76.0,139.0,6.0,NaN,0.0,7.0,...,9.47,5.67,3.26,4.44,18.540000,17.830000,18.195,81.67,NaN,25258015.0

In [ ]:
korea_gdp = [16.8, 17.0, 16.4, 17.1, 17.5, 18.4, 18.6, 19.5, 20.1, 22.5, 28.9, 28.7, 30.7, 32.2, 32.6, 28.5]
korea_gdp=[i*1000000000 for i in korea_gdp]
korea_gdp

[16800000000.0,
 17000000000.0,
 16399999999.999998,
 17100000000.000002,
 17500000000.0,
 18400000000.0,
 18600000000.0,
 19500000000.0,
 20100000000.0,
 22500000000.0,
 28900000000.0,
 28700000000.0,
 30700000000.0,
 32200000000.000004,
 32600000000.0,
 28500000000.0]

In [ ]:
df1.loc[df1[df1.Country=="Democratic People's Republic of Korea"].index,'GDP'] = korea_gdp

In [ ]:
df1.isna().sum()

Unnamed: 0                           0
Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                  0
Income composition of resources    160
Schooling                          160
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                           0
GDP                                  0
Population                           0
dtype: int64

In [ ]:
print(df1[df1.Schooling.isna()][['Country', 'Year']].to_string())

                                    Country  Year
673                                 Czechia  2000
674                                 Czechia  2001
675                                 Czechia  2002
676                                 Czechia  2003
677                                 Czechia  2004
678                                 Czechia  2005
679                                 Czechia  2006
680                                 Czechia  2007
681                                 Czechia  2008
682                                 Czechia  2009
683                                 Czechia  2010
684                                 Czechia  2011
685                                 Czechia  2012
686                                 Czechia  2013
687                                 Czechia  2014
688                                 Czechia  2015
689                           Côte d'Ivoire  2000
690                           Côte d'Ivoire  2001
691                           Côte d'Ivoire  2002
692                           Côte d'Ivoire  2003
693                           Côte d'Ivoire  2004
694                           Côte d'Ivoire  2005
695                           Côte d'Ivoire  2006
696                           Côte d'Ivoire  2007
697                           Côte d'Ivoire  2008
698                           Côte d'Ivoire  2009
699                           Côte d'Ivoire  2010
700                           Côte d'Ivoire  2011
701                           Côte d'Ivoire  2012
702                           Côte d'Ivoire  2013
703                           Côte d'Ivoire  2014
704                           Côte d'Ivoire  2015
705   Democratic People's Republic of Korea  2000
706   Democratic People's Republic of Korea  2001
707   Democratic People's Republic of Korea  2002
708   Democratic People's Republic of Korea  2003
709   Democratic People's Republic of Korea  2004
710   Democratic People's Republic of Korea  2005
711   Democratic People's Republic of Korea  2006
712   Democratic People's Republic of Korea  2007
713   Democratic People's Republic of Korea  2008
714   Democratic People's Republic of Korea  2009
715   Democratic People's Republic of Korea  2010
716   Democratic People's Republic of Korea  2011
717   Democratic People's Republic of Korea  2012
718   Democratic People's Republic of Korea  2013
719   Democratic People's Republic of Korea  2014
720   Democratic People's Republic of Korea  2015
721        Democratic Republic of the Congo  2000
722        Democratic Republic of the Congo  2001
723        Democratic Republic of the Congo  2002
724        Democratic Republic of the Congo  2003
725        Democratic Republic of the Congo  2004
726        Democratic Republic of the Congo  2005
727        Democratic Republic of the Congo  2006
728        Democratic Republic of the Congo  2007
729        Democratic Republic of the Congo  2008
730        Democratic Republic of the Congo  2009
731        Democratic Republic of the Congo  2010
732        Democratic Republic of the Congo  2011
733        Democratic Republic of the Congo  2012
734        Democratic Republic of the Congo  2013
735        Democratic Republic of the Congo  2014
736        Democratic Republic of the Congo  2015
2087                      Republic of Korea  2000
2088                      Republic of Korea  2001
2089                      Republic of Korea  2002
2090                      Republic of Korea  2003
2091                      Republic of Korea  2004
2092                      Republic of Korea  2005
2093                      Republic of Korea  2006
2094                      Republic of Korea  2007
2095                      Republic of Korea  2008
2096                      Republic of Korea  2009
2097                      Republic of Korea  2010
2098                      Republic of Korea  2011
2099                      Republic of Korea  2012
2100                      Republic of Korea  2013
2101                      Republic of Korea  2014
2102                      Republic of Korea  2015
2103                    Republic of Moldova  2000
2104                    Republic of Moldova  2001
2105                    Republic of Moldova  2002
2106                    Republic of Moldova  2003
2107                    Republic of Moldova  2004
2108                    Republic of Moldova  2005
2109                    Republic of Moldova  2006
2110                    Republic of Moldova  2007
2111                    Republic of Moldova  2008
2112                    Republic of Moldova  2009
2113                    Republic of Moldova  2010
2114                    Republic of Moldova  2011
2115                    Republic of Moldova  2012
2116                    Republic of Moldova  2013
2117                    Republic of Moldova  2014
2118                    Republic of Moldova  2015
2377                                Somalia  2000
2378                                Somalia  2001
2379                                Somalia  2002
2380                                Somalia  2003
2381                                Somalia  2004
2382                                Somalia  2005
2383                                Somalia  2006
2384                                Somalia  2007
2385                                Somalia  2008
2386                                Somalia  2009
2387                                Somalia  2010
2388                                Somalia  2011
2389                                Somalia  2012
2390                                Somalia  2013
2391                                Somalia  2014
2392                                Somalia  2015
2762                         United Kingdom  2000
2763                         United Kingdom  2001
2764                         United Kingdom  2002
2765                         United Kingdom  2003
2766                         United Kingdom  2004
2767                         United Kingdom  2005
2768                         United Kingdom  2006
2769                         United Kingdom  2007
2770                         United Kingdom  2008
2771                         United Kingdom  2009
2772                         United Kingdom  2010
2773                         United Kingdom  2011
2774                         United Kingdom  2012
2775                         United Kingdom  2013
2776                         United Kingdom  2014
2777                         United Kingdom  2015
2778                               Tanzania  2000
2779                               Tanzania  2001
2780                               Tanzania  2002
2781                               Tanzania  2003
2782                               Tanzania  2004
2783                               Tanzania  2005
2784                               Tanzania  2006
2785                               Tanzania  2007
2786                               Tanzania  2008
2787                               Tanzania  2009
2788                               Tanzania  2010
2789                               Tanzania  2011
2790                               Tanzania  2012
2791                               Tanzania  2013
2792                               Tanzania  2014
2793                               Tanzania  2015
2794               United States of America  2000
2795               United States of America  2001
2796               United States of America  2002
2797               United States of America  2003
2798               United States of America  2004
2799               United States of America  2005
2800               United States of America  2006
2801               United States of America  2007
2802               United States of America  2008
2803               United States of America  2009
2804               United States of America  2010
2805               United States of America  2011
2806               United States of America  2012
2807               United States of America  2013
2808               United States of America  2014
2809               United States of America  2015

In [ ]:
c1_list = df1[df1.Schooling.isna()].Country.unique()

In [ ]:
c2_list = df1[df1['Income composition of resources'].isna()].Country.unique()

In [ ]:
c1_list, c2_list

(array(['Czechia', "Côte d'Ivoire",
        "Democratic People's Republic of Korea",
        'Democratic Republic of the Congo', 'Republic of Korea',
        'Republic of Moldova', 'Somalia', 'United Kingdom', 'Tanzania',
        'United States of America'], dtype=object),
 array(['Czechia', "Côte d'Ivoire",
        "Democratic People's Republic of Korea",
        'Democratic Republic of the Congo', 'Republic of Korea',
        'Republic of Moldova', 'Somalia', 'United Kingdom', 'Tanzania',
        'United States of America'], dtype=object))

In [ ]:
c1_list == c2_list

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
rdf = pd.read_csv('/content/gdrive/MyDrive/Cleaned Dataset/required_data.csv')

In [ ]:
rdf.replace('USA',"United States of America",inplace=True)

In [ ]:
rdf.columns

Index(['Unnamed: 0', 'Country', 'Year', 'Avg. Years of Schooling',
       'HDI (Income Composition of Resources)'],
      dtype='object')

In [ ]:
rdf.rename(columns = {'Avg. Years of Schooling':'Schooling', 'HDI (Income Composition of Resources)':'Income composition of resources'}, inplace = True)

In [ ]:
merged_df = pd.merge(df1, rdf, on=['Country','Year'], how='outer')

In [ ]:
merged_df.head()

,Unnamed: 0_x,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,...,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population,Unnamed: 0_y,Schooling_y,Income composition of resources_y
0,0,Afghanistan,2000,Developing,54.8,321.0,88.0,0.01,10.424960,122.0,...,9.78,17.086667,17.830000,15.875,21.87,3.854235e+09,19542982.0,NaN,NaN,NaN
1,1,Afghanistan,2001,Developing,55.3,316.0,88.0,0.01,10.574728,122.0,...,9.64,17.116667,17.866667,15.925,21.88,3.854235e+09,19688632.0,NaN,NaN,NaN
2,2,Afghanistan,2002,Developing,56.2,3.0,88.0,0.01,16.887351,122.0,...,10.18,17.150000,17.903333,15.980,23.27,3.854235e+09,21000256.0,NaN,NaN,NaN
3,3,Afghanistan,2003,Developing,56.7,295.0,87.0,0.01,11.089053,122.0,...,10.40,17.146667,17.976667,16.030,24.67,4.539501e+09,22645130.0,NaN,NaN,NaN
4,4,Afghanistan,2004,Developing,57.0,293.0,87.0,0.02,15.296066,120.0,...,9.74,17.180000,18.010000,16.080,26.07,5.220824e+09,23553551.0,NaN,NaN,NaN

In [ ]:
merged_df.columns

Index(['Unnamed: 0_x', 'Country', 'Year', 'Status', 'Life expectancy',
       'Adult Mortality', 'infant deaths', 'Alcohol', 'percentage expenditure',
       'under-five deaths', 'Total expenditure', 'HIV/AIDS',
       'thinness 1-19 years', 'Income composition of resources_x',
       'Schooling_x', 'Male_suicide_rate', 'Female_suicide_rate',
       'suicide_rate', 'Male_homicides', 'Female_homicides', 'Homicides',
       'Male_bmi', 'Female_bmi', 'bmi', 'Sanitation', 'GDP', 'Population',
       'Unnamed: 0_y', 'Schooling_y', 'Income composition of resources_y'],
      dtype='object')

In [ ]:
merged_df['Schooling'] = merged_df['Schooling_x'].fillna(merged_df['Schooling_y'])
merged_df['Income composition of resources'] = merged_df['Income composition of resources_x'].fillna(merged_df['Income composition of resources_y'])

In [ ]:
merged_df.drop(['Unnamed: 0_x', 'Unnamed: 0_y', 'Income composition of resources_y', 'Income composition of resources_x', 'Schooling_x', 'Schooling_y'], axis=1, inplace=True)

In [ ]:
merged_df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure',
       'under-five deaths', 'Total expenditure', 'HIV/AIDS',
       'thinness 1-19 years', 'Male_suicide_rate', 'Female_suicide_rate',
       'suicide_rate', 'Male_homicides', 'Female_homicides', 'Homicides',
       'Male_bmi', 'Female_bmi', 'bmi', 'Sanitation', 'GDP', 'Population',
       'Schooling', 'Income composition of resources'],
      dtype='object')

In [ ]:
for c in merged_df[merged_df.Schooling.isna()].Country.unique():
  merged_df.loc[merged_df[merged_df.Country==c].index,'Schooling'] = merged_df[merged_df.Country==c]['Schooling'].fillna(0)
  merged_df.loc[merged_df[merged_df.Country==c].index,'Income composition of resources'] = merged_df[merged_df.Country==c]['Income composition of resources'].fillna(0)

In [ ]:
merged_df.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                            193
percentage expenditure               0
under-five deaths                    0
Total expenditure                  226
HIV/AIDS                             0
thinness 1-19 years                  0
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                           0
GDP                                  0
Population                           0
Schooling                            0
Income composition of resources      0
dtype: int64

In [ ]:
df1 = merged_df.copy()

Handling missing values in alcohol column

In [ ]:
df1[df1['Alcohol'].isna()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,Total expenditure,...,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population,Schooling,Income composition of resources
47,Algeria,2015,Developing,75.6,19.0,21.0,NaN,0.0,24.0,NaN,...,0.77,1.67,19.290,19.280,19.285,86.74,1.659790e+11,39543154.0,14.4,0.743
63,Angola,2015,Developing,52.4,335.0,66.0,NaN,0.0,98.0,NaN,...,3.47,10.05,16.875,17.535,17.210,47.37,8.721930e+10,28127721.0,11.4,0.531
79,Antigua and Barbuda,2015,Developing,76.4,13.0,0.0,NaN,0.0,0.0,NaN,...,1.16,2.41,20.760,20.495,20.625,87.50,1.336693e+09,89941.0,13.9,0.784
95,Argentina,2015,Developing,76.3,116.0,8.0,NaN,0.0,9.0,NaN,...,1.98,6.37,20.375,19.635,20.010,94.95,5.947490e+11,43131966.0,17.3,0.826
111,Armenia,2015,Developing,74.8,118.0,1.0,NaN,0.0,1.0,NaN,...,1.57,3.88,18.600,18.135,18.400,92.91,1.055334e+10,2878595.0,12.7,0.741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,Venezuela,2015,Developing,74.1,157.0,9.0,NaN,0.0,10.0,NaN,...,8.17,61.18,19.715,19.720,19.715,94.85,4.823590e+11,30529716.0,14.3,0.769
2879,Vietnam,2015,Developing,76.0,127.0,28.0,NaN,0.0,35.0,NaN,...,0.41,1.79,17.280,16.510,16.910,80.76,2.392580e+11,92191398.0,12.6,0.678
2895,Yemen,2015,Developing,65.7,224.0,37.0,NaN,0.0,47.0,NaN,...,4.56,8.58,17.200,17.335,17.265,51.57,4.244450e+10,28516545.0,9.0,0.499
2911,Zambia,2015,Developing,61.8,33.0,27.0,NaN,0.0,40.0,NaN,...,3.35,6.77,17.040,17.500,17.270,29.71,2.125122e+10,16248230.0,12.5,0.576
2927,Zimbabwe,2015,Developing,67.0,336.0,22.0,NaN,0.0,32.0,NaN,...,5.95,13.43,16.370,17.520,16.945,38.12,1.996312e+10,14154937.0,10.3,0.507

In [ ]:
alc_c = df1[df1['Alcohol'].isna()].Country.unique()
for c in alc_c:
  for b in df1.loc[df1[df1.Country==c].index, 'Alcohol'].isna():
    if b:
      df1.loc[df1[df1.Country==c].index, 'Alcohol'] = df1[df1.Country==c]['Alcohol'].fillna(method="ffill")

In [ ]:
df1[df1['Alcohol'].isna()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,Total expenditure,...,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population,Schooling,Income composition of resources
2400,South Sudan,2000,Developing,48.9,38.0,31.0,NaN,0.000000,50.0,NaN,...,7.43,19.12,18.201111,19.004444,16.461944,6.87,1.458625e+10,6114440.0,0.0,0.000
2401,South Sudan,2001,Developing,49.6,381.0,30.0,NaN,0.000000,49.0,NaN,...,7.28,18.62,18.243889,19.042222,16.496806,6.87,1.458625e+10,6394431.0,0.0,0.000
2402,South Sudan,2002,Developing,52.0,382.0,30.0,NaN,0.000000,48.0,NaN,...,7.07,18.08,18.300000,19.107222,16.536389,6.87,1.458625e+10,6686100.0,0.0,0.000
2403,South Sudan,2003,Developing,58.0,383.0,29.0,NaN,0.000000,46.0,NaN,...,6.83,17.56,18.347222,19.164444,16.568056,6.87,1.458625e+10,6992367.0,0.0,0.000
2404,South Sudan,2004,Developing,51.4,383.0,29.0,NaN,0.000000,45.0,NaN,...,6.59,16.99,18.409444,19.214444,16.599306,6.87,1.458625e+10,7317118.0,0.0,0.000
2405,South Sudan,2005,Developing,51.9,383.0,28.0,NaN,0.000000,44.0,NaN,...,6.37,16.35,18.455000,19.260556,16.627361,6.87,1.458625e+10,7662654.0,0.0,0.000
2406,South Sudan,2006,Developing,52.5,383.0,28.0,NaN,0.000000,43.0,NaN,...,6.18,15.83,18.503889,19.311111,16.651389,6.87,1.458625e+10,8029517.0,0.0,0.000
2407,South Sudan,2007,Developing,53.1,381.0,27.0,NaN,0.000000,43.0,NaN,...,6.07,15.33,18.556667,19.358889,16.673611,6.87,1.458625e+10,8417823.0,0.0,0.000
2408,South Sudan,2008,Developing,53.6,377.0,27.0,NaN,0.000000,42.0,NaN,...,6.01,14.95,18.609444,19.427778,16.690972,6.87,1.458625e+10,8823888.0,0.0,0.000
2409,South Sudan,2009,Developing,54.3,369.0,27.0,NaN,0.000000,42.0,NaN,...,5.86,14.53,18.671111,19.473333,16.710833,6.87,1.223126e+10,9229227.0,0.0,0.000
2410,South Sudan,2010,Developing,55.0,359.0,27.0,NaN,0.000000,41.0,NaN,...,5.88,14.29,16.393611,17.067361,16.729167,6.87,1.460207e+10,9714419.0,0.0,0.000
2411,South Sudan,2011,Developing,55.4,355.0,27.0,NaN,0.000000,41.0,NaN,...,5.88,14.11,16.428611,17.076250,16.750278,6.87,1.490731e+10,10243050.0,4.9,0.429
2412,South Sudan,2012,Developing,56.0,347.0,26.0,NaN,38.338232,40.0,2.77,...,5.86,13.90,16.468333,17.088194,16.775694,7.80,1.193147e+10,10701604.0,4.9,0.419
2413,South Sudan,2013,Developing,56.4,345.0,26.0,NaN,47.444530,40.0,2.62,...,5.93,14.02,16.508750,17.101667,16.803889,8.78,1.842647e+10,11106031.0,4.9,0.417
2414,South Sudan,2014,Developing,56.6,343.0,26.0,NaN,46.074469,39.0,2.74,...,6.10,14.32,16.551667,17.116944,16.833194,9.81,1.396221e+10,11213284.0,4.9,0.421
2415,South Sudan,2015,Developing,57.3,332.0,26.0,NaN,0.000000,39.0,NaN,...,6.36,14.65,16.595833,17.136389,16.864306,10.89,1.199780e+10,11194299.0,4.9,0.421

In [ ]:
df2 = df1[df1.Country!='South Sudan']

In [ ]:
df2.isna().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                              0
percentage expenditure               0
under-five deaths                    0
Total expenditure                  213
HIV/AIDS                             0
thinness 1-19 years                  0
Male_suicide_rate                    0
Female_suicide_rate                  0
suicide_rate                         0
Male_homicides                       0
Female_homicides                     0
Homicides                            0
Male_bmi                             0
Female_bmi                           0
bmi                                  0
Sanitation                           0
GDP                                  0
Population                           0
Schooling                            0
Income composition of resources      0
dtype: int64

total expenditure interpolate

In [ ]:
pd.DataFrame(df2.groupby(['Country'])['Total expenditure'].mean())

                     Total expenditure
Country
Afghanistan                   8.252500
Albania                       5.945625
Algeria                       4.604000
Angola                        3.919333
Antigua and Barbuda           4.791333
...                                ...
Venezuela                     4.998667
Vietnam                       5.977333
Yemen                         5.005333
Zambia                        5.824000
Zimbabwe                      6.158667

[182 rows x 1 columns]

In [ ]:
df2[df2['Total expenditure'].isna()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,Total expenditure,...,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population,Schooling,Income composition of resources
47,Algeria,2015,Developing,75.6,19.0,21.0,0.01,0.0,24.0,NaN,...,0.77,1.67,19.290,19.280,19.285,86.74,1.659790e+11,39543154.0,14.4,0.743
63,Angola,2015,Developing,52.4,335.0,66.0,8.33,0.0,98.0,NaN,...,3.47,10.05,16.875,17.535,17.210,47.37,8.721930e+10,28127721.0,11.4,0.531
79,Antigua and Barbuda,2015,Developing,76.4,13.0,0.0,8.56,0.0,0.0,NaN,...,1.16,2.41,20.760,20.495,20.625,87.50,1.336693e+09,89941.0,13.9,0.784
95,Argentina,2015,Developing,76.3,116.0,8.0,7.93,0.0,9.0,NaN,...,1.98,6.37,20.375,19.635,20.010,94.95,5.947490e+11,43131966.0,17.3,0.826
111,Armenia,2015,Developing,74.8,118.0,1.0,3.91,0.0,1.0,NaN,...,1.57,3.88,18.600,18.135,18.400,92.91,1.055334e+10,2878595.0,12.7,0.741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,Venezuela,2015,Developing,74.1,157.0,9.0,6.47,0.0,10.0,NaN,...,8.17,61.18,19.715,19.720,19.715,94.85,4.823590e+11,30529716.0,14.3,0.769
2879,Vietnam,2015,Developing,76.0,127.0,28.0,4.09,0.0,35.0,NaN,...,0.41,1.79,17.280,16.510,16.910,80.76,2.392580e+11,92191398.0,12.6,0.678
2895,Yemen,2015,Developing,65.7,224.0,37.0,0.01,0.0,47.0,NaN,...,4.56,8.58,17.200,17.335,17.265,51.57,4.244450e+10,28516545.0,9.0,0.499
2911,Zambia,2015,Developing,61.8,33.0,27.0,0.01,0.0,40.0,NaN,...,3.35,6.77,17.040,17.500,17.270,29.71,2.125122e+10,16248230.0,12.5,0.576
2927,Zimbabwe,2015,Developing,67.0,336.0,22.0,6.50,0.0,32.0,NaN,...,5.95,13.43,16.370,17.520,16.945,38.12,1.996312e+10,14154937.0,10.3,0.507

In [ ]:
df2['Total expenditure'] = df2.groupby('Country')['Total expenditure'].transform(lambda x: x.fillna(x.mean()))

<ipython-input-64-a3895c1801e7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Total expenditure'] = df2.groupby('Country')['Total expenditure'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
df2.isna().sum()

Country                             0
Year                                0
Status                              0
Life expectancy                     0
Adult Mortality                     0
infant deaths                       0
Alcohol                             0
percentage expenditure              0
under-five deaths                   0
Total expenditure                  32
HIV/AIDS                            0
thinness 1-19 years                 0
Male_suicide_rate                   0
Female_suicide_rate                 0
suicide_rate                        0
Male_homicides                      0
Female_homicides                    0
Homicides                           0
Male_bmi                            0
Female_bmi                          0
bmi                                 0
Sanitation                          0
GDP                                 0
Population                          0
Schooling                           0
Income composition of resources     0
dtype: int64

In [ ]:
df2[df2['Total expenditure'].isna()]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,under-five deaths,Total expenditure,...,Female_homicides,Homicides,Male_bmi,Female_bmi,bmi,Sanitation,GDP,Population,Schooling,Income composition of resources
704,Democratic People's Republic of Korea,2000,Developing,65.4,192.0,18.0,3.52,0.0,25.0,NaN,...,3.60,6.06,19.083333,18.670000,17.420,75.20,1.680000e+10,23367059.0,0.0,0.0
705,Democratic People's Republic of Korea,2001,Developing,66.6,177.0,16.0,2.53,0.0,21.0,NaN,...,3.50,5.50,19.126667,18.653333,17.460,75.20,1.700000e+10,23512522.0,0.0,0.0
706,Democratic People's Republic of Korea,2002,Developing,67.6,167.0,14.0,3.08,0.0,18.0,NaN,...,3.48,5.25,19.156667,18.666667,17.500,75.20,1.640000e+10,23638411.0,0.0,0.0
707,Democratic People's Republic of Korea,2003,Developing,68.1,165.0,12.0,3.13,0.0,15.0,NaN,...,3.67,5.15,19.193333,18.640000,17.530,75.21,1.710000e+10,23781707.0,0.0,0.0
708,Democratic People's Republic of Korea,2004,Developing,68.4,165.0,11.0,3.13,0.0,14.0,NaN,...,3.53,4.39,19.223333,18.656667,17.565,75.22,1.750000e+10,23948930.0,0.0,0.0
709,Democratic People's Republic of Korea,2005,Developing,68.5,165.0,10.0,3.21,0.0,13.0,NaN,...,3.38,4.70,19.260000,18.670000,17.605,75.23,1.840000e+10,24100982.0,0.0,0.0
710,Democratic People's Republic of Korea,2006,Developing,68.5,165.0,10.0,3.28,0.0,12.0,NaN,...,3.38,4.67,19.300000,18.693333,17.650,75.24,1.860000e+10,24235761.0,0.0,0.0
711,Democratic People's Republic of Korea,2007,Developing,68.5,166.0,9.0,3.13,0.0,12.0,NaN,...,3.60,4.87,19.343333,18.716667,17.705,75.92,1.950000e+10,24356506.0,0.0,0.0
712,Democratic People's Republic of Korea,2008,Developing,68.6,164.0,9.0,3.16,0.0,12.0,NaN,...,3.57,4.79,19.386667,18.746667,17.755,76.61,2.010000e+10,24469047.0,0.0,0.0
713,Democratic People's Republic of Korea,2009,Developing,68.7,161.0,9.0,3.35,0.0,11.0,NaN,...,3.60,4.82,19.433333,18.776667,17.815,77.32,2.250000e+10,24581509.0,0.0,0.0
714,Democratic People's Republic of Korea,2010,Developing,69.0,157.0,8.0,3.12,0.0,10.0,NaN,...,3.53,4.76,18.175000,17.560000,17.875,78.03,2.890000e+10,24686435.0,0.0,0.0
715,Democratic People's Republic of Korea,2011,Developing,69.4,153.0,8.0,3.39,0.0,10.0,NaN,...,3.45,4.68,18.245000,17.610000,17.935,78.75,2.870000e+10,24783789.0,0.0,0.0
716,Democratic People's Republic of Korea,2012,Developing,69.8,149.0,7.0,3.61,0.0,9.0,NaN,...,3.37,4.60,18.320000,17.660000,18.000,79.47,3.070000e+10,24887770.0,0.0,0.0
717,Democratic People's Republic of Korea,2013,Developing,71.0,146.0,6.0,3.35,0.0,8.0,NaN,...,3.32,4.53,18.390000,17.720000,18.060,80.20,3.220000e+10,25001819.0,0.0,0.0
718,Democratic People's Republic of Korea,2014,Developing,73.0,142.0,6.0,0.01,0.0,8.0,NaN,...,3.29,4.49,18.460000,17.770000,18.125,80.93,3.260000e+10,25126131.0,0.0,0.0
719,Democratic People's Republic of Korea,2015,Developing,76.0,139.0,6.0,0.01,0.0,7.0,NaN,...,3.26,4.44,18.540000,17.830000,18.195,81.67,2.850000e+10,25258015.0,0.0,0.0
2368,Somalia,2000,Developing,55.0,355.0,45.0,0.01,0.0,74.0,NaN,...,3.03,6.81,18.003333,18.723333,16.720,20.17,4.577000e+09,8721465.0,0.0,0.0
2369,Somalia,2001,Developing,57.0,352.0,46.0,0.01,0.0,75.0,NaN,...,2.97,6.67,18.040000,18.780000,16.765,20.78,4.577000e+09,9070747.0,0.0,0.0
2370,Somalia,2002,Developing,58.0,348.0,47.0,0.01,0.0,77.0,NaN,...,2.97,6.59,18.110000,18.836667,16.810,21.38,4.577000e+09,9411103.0,0.0,0.0
2371,Somalia,2003,Developing,51.1,344.0,48.0,0.01,0.0,78.0,NaN,...,2.91,6.49,18.143333,18.893333,16.850,22.13,4.577000e+09,9758281.0,0.0,0.0
2372,Somalia,2004,Developing,51.2,341.0,49.0,0.01,0.0,80.0,NaN,...,2.86,6.39,18.213333,18.910000,16.895,22.88,4.577000e+09,10117354.0,0.0,0.0
2373,Somalia,2005,Developing,51.6,334.0,50.0,0.01,0.0,82.0,NaN,...,2.85,6.31,18.246667,18.963333,16.935,23.87,4.577000e+09,10467292.0,0.0,0.0
2374,Somalia,2006,Developing,51.5,337.0,51.0,0.01,0.0,83.0,NaN,...,2.89,6.28,18.313333,19.010000,16.965,24.86,4.577000e+09,10784973.0,0.0,0.0
2375,Somalia,2007,Developing,51.5,34.0,52.0,0.01,0.0,84.0,NaN,...,2.87,6.17,18.376667,19.053333,17.000,24.56,4.577000e+09,11118092.0,0.0,0.0
2376,Somalia,2008,Developing,51.9,336.0,52.0,0.01,0.0,84.0,NaN,...,2.85,6.04,18.410000,19.100000,17.025,25.90,4.577000e+09,11444870.0,0.0,0.0
2377,Somalia,2009,Developing,52.2,335.0,52.0,0.01,0.0,84.0,NaN,...,2.94,6.02,18.470000,19.110000,17.055,27.26,4.577000e+09,11730037.0,0.0,0.0
2378,Somalia,2010,Developing,52.4,336.0,52.0,0.01,0.0,83.0,NaN,...,2.88,6.03,16.750000,17.440000,17.095,28.63,4.577000e+09,12026649.0,0.0,0.0
2379,Somalia,2011,Developing,53.1,329.0,51.0,0.01,0.0,82.0,NaN,...,2.85,5.95,16.800000,17.465000,17.130,30.02,4.577000e+09,12216837.0,0.0,0.0
2380,Somalia,2012,Developing,53.1,336.0,51.0,0.01,0.0,82.0,NaN,...,2.74,5.69,16.855000,17.500000,17.175,31.00,4.577000e+09,12440326.0,0.0,0.0
2381,Somalia,2013,Developing,54.2,318.0,51.0,0.01,0.0,81.0,NaN,...,2.71,5.65,16.905000,17.535000,17.220,32.00,4.577000e+09,12852485.0,0.0,0.0
2382,Somalia,2014,Developing,54.3,321.0,51.0,0.01,0.0,80.0,NaN,...,2.71,5.64,16.965000,17.570000,17.265,33.01,5.025000e+09,13309235.0,0.0,0.0
2383,Somalia,2015,Developing,55.0,312.0,50.0,0.01,0.0,80.0,NaN,...,2.72,5.64,17.015000,17.605000,17.305,34.03,5.335000e+09,13763906.0,0.0,0.0

In [ ]:
df2.loc[705,"Total expenditure"]=14
df2.loc[2377,"Total expenditure"]=21

In [ ]:
df2['Total expenditure'] = df2.groupby('Country')['Total expenditure'].transform(lambda x: x.fillna(x.mean()))

<ipython-input-68-a3895c1801e7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Total expenditure'] = df2.groupby('Country')['Total expenditure'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
df2.isna().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
under-five deaths                  0
Total expenditure                  0
HIV/AIDS                           0
thinness 1-19 years                0
Male_suicide_rate                  0
Female_suicide_rate                0
suicide_rate                       0
Male_homicides                     0
Female_homicides                   0
Homicides                          0
Male_bmi                           0
Female_bmi                         0
bmi                                0
Sanitation                         0
GDP                                0
Population                         0
Schooling                          0
Income composition of resources    0
dtype: int64

In [ ]:
df2.to_csv("cleaned_data.csv")

In [ ]:
df2.shape

(2912, 26)